version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6.10-browsers
    steps:
      - checkout
      - run:
          name: build
          command: ls
      - run:
          name: Print the Current Time
          command: date
