version: 2
jobs:
  docker:
      - image: debian:stretch
  build:
    steps:
      - checkout
      - run:
          name: build
          command: ls
      - run:
          name: Print the Current Time
          command: date
